version: 2.1

jobs:
  CPP:
    docker:
      - image: ptru/gtest
    steps:
      - checkout
      - run:
          name: Install curl, lcov, and valgrind
          command: apt update && apt -y install curl lcov valgrind
      - run:
          name: Build test executables
          command: cd C++ && make
      - run:
          name: Run unit tests
          command: |
            cd C++/bin
            for file in *
            do
                echo "Running $file";
                ./$file;
                printf "\n\n";
            done
      - run:
          name: Run memory leak tests
          command: |
            cd C++/bin
            for file in *
            do
                echo "Running $file";
                bash ../util/memory_leak_test.sh $file
                printf "\n\n";
            done
      - run:
          name: "Create code coverage"
          command: |
            cd C++
            bash util/get_cov.sh
            bash <(curl -s https://codecov.io/bash) -f *.info

workflows:
  version: 2
  run:
    jobs:
      - cpp