version: 2.1

jobs:
  test:
    docker:
      - image: ptru/gtest
    steps:
      - checkout
      - run:
          name: Install curl
          command: apt update && apt -y install curl
      - run:
          name: Build test executables
          command: cd C++/tests && make
      - run:
          name: Run FibonacciHeap tests
          command: ./C++/tests/fibheap_test
      - run:
          name: Run Graph tests
          command: ./C++/tests/graph_test
      - run:
          name: Run Trie tests
          command: ./C++/tests/trie_test
      - run:
          name: "Upload code coverage"
          command: cd C++/tests && make cov && cd ../ && bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  run:
    jobs:
      - test