version: 2.1

jobs:
  test:
    docker:
      - image: ptru/gtest
    steps:
      - checkout
      - run:
          name: Build test executables
          command: cd Common-Functions/C++/tests && make
      - run:
          name: Run FibonacciHeap tests
          command: ./fibheap_tests
      - run:
          name: Run Graph tests
          command: ./graph_tests
      - run:
          name: Run Trie tests
          command: ./trie_tests
      - run:
          name: "Create & upload codecov report"
          command: make cov && bash <(curl -s https://codecov.io/bash) -f cov.info