version: 2.1

jobs:
  test:
    docker:
      - image: ptru/gtest
    steps:
      - checkout
      - run:
          name: Build test executables
          command: cd C++/tests && make
      - run:
          name: Run FibonacciHeap tests
          command: ls && ls C++/tests && ./C++/tests/fibheap_tests
      - run:
          name: Run Graph tests
          command: ./C++/tests/graph_tests
      - run:
          name: Run Trie tests
          command: ./C++/tests/trie_tests
      - run:
          name: "Create & upload codecov report"
          command: cd C++/tests && make cov && bash <(curl -s https://codecov.io/bash) -f cov.info

workflows:
  version: 2
  run:
    jobs:
      - test