version: 2.1

jobs:
  test:
    docker:
      - image: ptru/gtest
    steps:
      - checkout
      - run:
          name: Install curl, lcov, and valgrind
          command: apt update && apt -y install curl lcov valgrind
      - run:
          name: Build test executables
          command: cd C++ && make
      - run:
          name: Run FibonacciHeap tests
          command: ./C++/fibheap_test
      - run:
          name: Run FibonacciHeap memory leak test
          command: bash ./C++/memory_leak_test.sh ./C++/fibheap_test
      - run:
          name: Run Graph tests
          command: ./C++/graph_test
      - run:
          name: Run Graph memory leak test
          command: bash ./C++/memory_leak_test.sh ./C++/graph_test
      - run:
          name: Run Trie tests
          command: ./C++/trie_test
      - run:
          name: Run Trie memory leak test
          command: bash ./C++/memory_leak_test.sh ./C++/trie_test
      - run:
          name: "Create code coverage"
          command: |
            cd C++
            bash get_cov.sh
            bash <(curl -s https://codecov.io/bash) -f cov_filtered.info

workflows:
  version: 2
  run:
    jobs:
      - test